image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip

pages:
  stage: deploy
  script:
  - mkdir Dist
  - cp -R Source/* Dist/
  - cd Dist
  - pip3 install -r requirements.txt
  - python3 Generate.py
  artifacts:
    paths:
    - Dist
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
