image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip wkhtmltopdf
  - pip3 install -r Source/requirements.txt

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -R Source/* public/
  - cd public
  - python3 Generate.py
  - wkhtmltoimage --height 720 --quality 0 "https://octospacc.gitlab.io/WebPinBoard/" "Screenshot.png"
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
