image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -R Source/* public/
  - cd public
  - pip3 install -r requirements.txt
  - python3 Generate.py
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
